### ISSUE TITLE
How can you get the ElasticFlow\scheduler\throughputs_T4?

### ISSUE THREAD

**Issue by QingweiJi** [gudiandian/ElasticFlow-artifact#2] opened 2023-09-21 08:19 UTC
Hi! 
I really want to know how you got the T4 data, by running Pollux's code or was it provided directly (I can't seem to find it)?
But it is obvious that the existing data of T4 cannot be used for ElasticFlow because it does not include the number of iterations of the model corresponding to the task under different global batch sizes and different numbers of GPUs.

**Comment by gudiandian** [comment] 2023-09-21 08:22
The T4 data is in [https://github.com/gudiandian/ElasticFlow/tree/main/pollux/pollux_simulator/traces](https://github.com/gudiandian/ElasticFlow/tree/main/pollux/pollux_simulator/traces), it was provided by [https://github.com/petuum/adaptdl](https://github.com/petuum/adaptdl).

**Comment by QingweiJi** [comment] 2023-09-21 08:53
OK, I know it now, but the data provided cannot be directly used in the code built by ElasticFlow, because I encountered many problems when executing the command "source run_fig8a.sh" at first

**Comment by gudiandian** [comment] 2023-09-21 08:58
Could you please provide more details? Are you running testbed experiments or simulation experiments? What is your environment, your command line, and the logs?

**Comment by QingweiJi** [comment] 2023-09-21 11:57
I did the simulation experiment on my laptop and followed the steps provided at https://github.com/gudiandian/ElasticFlow/tree/main/ElasticFlow step by step. However, when executing the command ’**source run_fig8a.sh**‘ some problems occurred.
![1](https://github.com/gudiandian/ElasticFlow/assets/34529379/a9ffd15d-e537-438a-a5de-f44722e22445)
（1）**traces_for_ElasticFlow/elasticVpollux_e.csv** does not exist. After the command "tar -xvzf elasticflow-traces/data/elasticflow-traces.tar.gz -C ElasticFlow/traces_for_ElasticFlow/" is executed, there are only cluster01-cluster10, 195job, philly and resnet Related traces
（2）In the document "run_fig8a.sh" need execute the comand "python3 scheduler.py --cluster_spec=${cluster_spec} --print --scheme=${placement} --trace_file=${job_file}  --schedule=${s} --log_path=${log_name} --simulation=True --scheduling_slot=60 --gpu_type=T4&" 
However, due to the data in T4 is incomplete, the following situation occurs. For example, the model_name of job 1 is bert and the batch_size is 64, but the content of bert.csv in the T4 folder is as follows: 
global_batch_size,1,2,4,8,16 ,32,64
384,0.03440690542609718,0.07202256803269298,0.14271706368522086,0.19352567710981528,0.3595788817208245,0.4890484273336248 6,0.4692708078100514. 
As a result, wherever the global dictionary THROUGHPUTS is used in the code, an error will be reported, indicating that the dictionary read is empty.
I use only one job to test this, and the problem is as follows:
![2](https://github.com/gudiandian/ElasticFlow/assets/34529379/e79ea7f8-5f3e-4172-9851-3daddda78699)
After troubleshooting the problem, I found that when the gpu_type is specified as T4, the global dictionary cannot be mapped to the throughputs result file. This is also the reason why I initially raised the issue of where the data in the T4 folder comes from.

**Comment by gudiandian** [comment] 2023-09-21 14:33
You met the problem because the job traces you used are for A100, not T4. The trace we used for T4 is not public because of the policy of Microsoft. Specifying the GPU type to be A100 instead of T4 should work. Or you can generate a trace that works for the T4 throughputs by yourself. In your case, if you want to test with only one job on T4 GPU, the batch size of your job should be 384 instead of 64.

To make you better understand this: The T4 throughputs were all provided by adaptdl. The configurations (including DNN model, number of GPUs, batch sizes, etc.) that we profiled on A100 are different from the provided configurations of T4. Therefore, the experiments for T4 and for A100 can not share the same job traces.

**Comment by gudiandian** [comment] 2023-09-21 14:36
Also, please feel free to run any scheduling algorithm on any available trace with `python scheduler.py xxx` instead of executing the scripts. Those scripts are only for the AE to strictly reproducing the results in the paper ^_^

**Comment by QingweiJi** [comment] 2023-09-22 02:40
> You met the problem because the job traces you used are for A100, not T4. The trace we used for T4 is not public because of the policy of Microsoft. Specifying the GPU type to be A100 instead of T4 should work. Or you can generate a trace that works for the T4 throughputs by yourself. In your case, if you want to test with only one job on T4 GPU, the batch size of your job should be 384 instead of 64.
> 
> To make you better understand this: The T4 throughputs were all provided by adaptdl. The configurations (including DNN model, number of GPUs, batch sizes, etc.) that we profiled on A100 are different from the provided configurations of T4. Therefore, the experiments for T4 and for A100 can not share the same job traces.

This is sad news, but thank you very much for your reply. In addition, can the throughput results on T4 GPU be obtained only through real experimental testing? Or can it be artificially synthesized through the formula in Pollux paper?

**Comment by QingweiJi** [comment] 2023-09-22 02:48
> Also, please feel free to run any scheduling algorithm on any available trace with `python scheduler.py xxx` instead of executing the scripts. Those scripts are only for the AE to strictly reproducing the results in the paper ^_^

Yes, after I failed to execute the run_fig script directly, I started by using 
`"python3 scheduler.py --cluster_spec=cluster_specs/n1g4.csv --print --scheme=elastic --trace_file=test.csv --schedule =ef-accessctrl --simulation=True --scheduling_slot=60 --gpu_type=A100" ` configuration parameters to execute different schedulers. But for chronus, this method does not seem to work.  Since in **run_fig8a.sh**, if you want to use the chronus scheduler, you need to convert the elasticflow trace and other information before it can be used by chronus. So for chronus, how should I deal with it? 
![3](https://github.com/gudiandian/ElasticFlow/assets/34529379/de80e34d-9a47-4ba3-8730-a6cd66355d54)

**Comment by gudiandian** [comment] 2023-09-22 03:04
> > You met the problem because the job traces you used are for A100, not T4. The trace we used for T4 is not public because of the policy of Microsoft. Specifying the GPU type to be A100 instead of T4 should work. Or you can generate a trace that works for the T4 throughputs by yourself. In your case, if you want to test with only one job on T4 GPU, the batch size of your job should be 384 instead of 64.
> > To make you better understand this: The T4 throughputs were all provided by adaptdl. The configurations (including DNN model, number of GPUs, batch sizes, etc.) that we profiled on A100 are different from the provided configurations of T4. Therefore, the experiments for T4 and for A100 can not share the same job traces.
> 
> This is sad news, but thank you very much for your reply. In addition, can the throughput results on T4 GPU be obtained only through real experimental testing? Or can it be artificially synthesized through the formula in Pollux paper?

As I mentioned before, the throughputs data for T4 was **provided** by adaptdl. The data was collected on T4 GPU by the authors of Pollux. If you want more data, you have to collect it.

**Comment by gudiandian** [comment] 2023-09-22 03:07
> > Also, please feel free to run any scheduling algorithm on any available trace with `python scheduler.py xxx` instead of executing the scripts. Those scripts are only for the AE to strictly reproducing the results in the paper ^_^
> 
> Yes, after I failed to execute the run_fig script directly, I started by using `"python3 scheduler.py --cluster_spec=cluster_specs/n1g4.csv --print --scheme=elastic --trace_file=test.csv --schedule =ef-accessctrl --simulation=True --scheduling_slot=60 --gpu_type=A100" ` configuration parameters to execute different schedulers. But for chronus, this method does not seem to work. Since in **run_fig8a.sh**, if you want to use the chronus scheduler, you need to convert the elasticflow trace and other information before it can be used by chronus. So for chronus, how should I deal with it? ![3](https://user-images.githubusercontent.com/34529379/269815094-de80e34d-9a47-4ba3-8730-a6cd66355d54.png)

What do you mean by "this method does not seem to work"?
Just replace the name of the trace file to whatever trace file you are using should work, for example
```
cd ../chronus-scheduler/utils
# get trace and namelist
python3 convert_ef_trace_to_chronus.py -t ../../traces_for_ElasticFlow/test.csv -o ../../traces_for_chronus/test.csv
python3 get_name_list.py -t ../../traces_for_chronus/test.csv -o ../../traces_for_chronus/test.lst
cd ..
python3 main.py --schedule=time-aware-with-lease --trace=../traces_for_chronus/test.csv --save_log_dir=../../plot_figure/logs/figure8a/chronus --ident=chronus --aggressive=True --mip_objective=adaptive --placement=local_search --profile=True --check_time_interval=60 --disable_turn_off=True --num_node_p_switch=16 --lease_term_interval=240 --name_list=../traces_for_chronus/elasticVpollux_e.lst --simulation=True --gpu_type=A100 --num_gpu_p_node=8
cd ../scheduler
```

**Comment by QingweiJi** [comment] 2023-09-22 03:12
> > > Also, please feel free to run any scheduling algorithm on any available trace with `python scheduler.py xxx` instead of executing the scripts. Those scripts are only for the AE to strictly reproducing the results in the paper ^_^
> > 
> > 
> > Yes, after I failed to execute the run_fig script directly, I started by using `"python3 scheduler.py --cluster_spec=cluster_specs/n1g4.csv --print --scheme=elastic --trace_file=test.csv --schedule =ef-accessctrl --simulation=True --scheduling_slot=60 --gpu_type=A100" ` configuration parameters to execute different schedulers. But for chronus, this method does not seem to work. Since in **run_fig8a.sh**, if you want to use the chronus scheduler, you need to convert the elasticflow trace and other information before it can be used by chronus. So for chronus, how should I deal with it? ![3](https://user-images.githubusercontent.com/34529379/269815094-de80e34d-9a47-4ba3-8730-a6cd66355d54.png)
> 
> What do you mean by "this method does not seem to work"? Just replace the name of the trace file to whatever trace file you are using should work, for example
> 
> ```
> cd ../chronus-scheduler/utils
> # get trace and namelist
> python3 convert_ef_trace_to_chronus.py -t ../../traces_for_ElasticFlow/test.csv -o ../../traces_for_chronus/test.csv
> python3 get_name_list.py -t ../../traces_for_chronus/test.csv -o ../../traces_for_chronus/test.lst
> cd ..
> python3 main.py --schedule=time-aware-with-lease --trace=../traces_for_chronus/test.csv --save_log_dir=../../plot_figure/logs/figure8a/chronus --ident=chronus --aggressive=True --mip_objective=adaptive --placement=local_search --profile=True --check_time_interval=60 --disable_turn_off=True --num_node_p_switch=16 --lease_term_interval=240 --name_list=../traces_for_chronus/elasticVpollux_e.lst --simulation=True --gpu_type=A100 --num_gpu_p_node=8
> cd ../scheduler
> ```

I just need to replace it with the trace.csv I need and execute run_ Fig8a. sh?

**Comment by gudiandian** [comment] 2023-09-22 03:31
@QingweiJi I am sorry that I deleted your question by mistake. 
Just replace the file name and give it a try. However, I suggest you run each scheduler one by one in command lines. This helps a lot when debugging.

**Comment by QingweiJi** [comment] 2023-09-22 06:57
> @QingweiJi I am sorry that I deleted your question by mistake. Just replace the file name and give it a try. However, I suggest you run each scheduler one by one in command lines. This helps a lot when debugging.

Unfortunately, I ran chronus in two ways, but could not get the result after running. It showed that the trace of ElasticFlow was not converted into the form of chronus, which caused the scheduler to not be executed and the output result was empty.

```
cd ../chronus-scheduler/utils
# get trace and namelist
python3 convert_ef_trace_to_chronus.py -t ../../traces_for_ElasticFlow/test.csv -o ../../traces_for_chronus/test.csv
python3 get_name_list.py -t ../../traces_for_chronus/test.csv -o ../../traces_for_chronus/test.lst
cd ..
python3 main.py --schedule=time-aware-with-lease --trace=../traces_for_chronus/test.csv --save_log_dir=../../plot_figure/logs/figure8a/chronus --ident=chronus --aggressive=True --mip_objective=adaptive --placement=local_search --profile=True --check_time_interval=60 --disable_turn_off=True --num_node_p_switch=16 --lease_term_interval=240 --name_list=../traces_for_chronus/test.lst --simulation=True --gpu_type=A100 --num_gpu_p_node=8
cd ../scheduler
```

The first way:

![4](https://github.com/gudiandian/ElasticFlow/assets/34529379/93bec149-4cc0-468b-bcbc-aba349eb8c9e)

The second way:

![5](https://github.com/gudiandian/ElasticFlow/assets/34529379/db17fde3-5265-4a4e-a963-9db8bd2cba51)

**Comment by gudiandian** [comment] 2023-09-22 08:04
What are the contents of `../../traces_for_chronus/test.csv` and `../../traces_for_chronus/test.lst` on your laptop? 

Besides, it is not necessary to convert the traces in my repo if you want to try the Chronus scheduler. Please refer to [this repo](https://github.com/S-Lab-System-Group/ChronusArtifact) for the details of Chronus.

**Comment by QingweiJi** [comment] 2023-09-22 08:13
> What are the contents of `../../traces_for_chronus/test.csv` and `../../traces_for_chronus/test.lst` on your laptop?
> 
> Besides, it is not necessary to convert the traces in my repo if you want to try the Chronus scheduler. Please refer to [this repo](https://github.com/S-Lab-System-Group/ChronusArtifact) for the details of Chronus.

The job information in /traces_for_ElasticFlow/test.csv is the first five jobs I extracted from /traces_for_ElasticFlow/cluster01.csv, which is just for test different scheduler. Actually, I have used the chronus scheduler before and it ran successfully. But I am  very confused about why there is no output when I execute the command in run_fig8a.shell about chronus?

**Comment by gudiandian** [comment] 2023-09-22 08:32
The information that you provided is far from enough for me to debug for you because the script runs perfectly on my laptop.
<img width="932" alt="image" src="https://github.com/gudiandian/ElasticFlow/assets/23579389/0322fbca-cc21-4838-b1a6-50e5898fd59b">
 If you have run Chronus successfully before, then there is no need for you to run Chronus in this repo, because I barely modified anything. I will close this issue if there is no further question about ElasticFlow.

**Closed as completed by gudiandian** 2023-09-22 08:32 UTC

**Comment by QingweiJi** [comment] 2023-09-22 08:39
> The information that you provided is far from enough for me to debug for you because the script runs perfectly on my laptop. If you have run Chronus successfully before, then there is no need for you to run Chronus in this repo, because I barely modified anything. I will close this issue if there is no further question about ElasticFlow.

If you have barely modified chronus, then I have no problem to trouble you. Thanks for your reply!

**Comment by gudiandian** [comment] 2023-09-22 08:44
> > The information that you provided is far from enough for me to debug for you because the script runs perfectly on my laptop. If you have run Chronus successfully before, then there is no need for you to run Chronus in this repo, because I barely modified anything. I will close this issue if there is no further question about ElasticFlow.
> 
> If you have barely modified chronus, then I have no problem to trouble you. Thanks for your reply!

And thank you for trying out our artifact! Hope that you can resolve your problem soon.
